name: tests for lifebit-ai/phewas
# This workflow is triggered on pushes and PRs to the repository.
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: General test with binary trait
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test
  
  test_coloc_binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: General test with binary trait and coloc binary
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_coloc_binary
  test_coloc_quantitative:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nxf_ver: ['20.01.0', '']
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          export NXF_VER=${{ matrix.nxf_ver }}
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: General test with binary trait and coloc quantitative
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_coloc_quantitative